#All .yml files extend the configurations defined in this file

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: george
spring:
  cloud:
    config:
      override-system-properties: false  #Doesn't override the configuration in specific .yml file

management:
  tracing:
    sampling:
      probability: 1.0